services:
  backend:
    restart: always
    environment:
      APP_PG__HOST: 'postgres'

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:17.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_main
      POSTGRES_PASSWORD: db_main
      POSTGRES_DB: db_main
      PGUSER: db_main
      PGPASSWORD: db_main
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ".data/pg/:/var/lib/postgresql/data/"